# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'juli_style_relode.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1038, 775)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_search = QtGui.QPushButton(Form)
        self.pushButton_search.setObjectName(_fromUtf8("pushButton_search"))
        self.gridLayout.addWidget(self.pushButton_search, 4, 0, 1, 3)
        self.progressBar_play = QtGui.QProgressBar(Form)
        self.progressBar_play.setProperty("value", 0)
        self.progressBar_play.setFormat(_fromUtf8(""))
        self.progressBar_play.setObjectName(_fromUtf8("progressBar_play"))
        self.gridLayout.addWidget(self.progressBar_play, 1, 1, 1, 2)
        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.textBrowser_display = QtGui.QTextBrowser(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_display.sizePolicy().hasHeightForWidth())
        self.textBrowser_display.setSizePolicy(sizePolicy)
        self.textBrowser_display.setMaximumSize(QtCore.QSize(167772, 16777215))
        self.textBrowser_display.setObjectName(_fromUtf8("textBrowser_display"))
        self.gridLayout_3.addWidget(self.textBrowser_display, 0, 1, 1, 1)
        self.textBrowser_play = QtGui.QTextBrowser(self.groupBox)
        self.textBrowser_play.setObjectName(_fromUtf8("textBrowser_play"))
        self.gridLayout_3.addWidget(self.textBrowser_play, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton_home = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_home.setObjectName(_fromUtf8("pushButton_home"))
        self.gridLayout_2.addWidget(self.pushButton_home, 2, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 3, 4, 1, 1)
        self.lineEdit_homes = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_homes.setText(_fromUtf8(""))
        self.lineEdit_homes.setObjectName(_fromUtf8("lineEdit_homes"))
        self.gridLayout_2.addWidget(self.lineEdit_homes, 3, 5, 1, 1)
        self.lineEdit_home = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_home.setText(_fromUtf8(""))
        self.lineEdit_home.setObjectName(_fromUtf8("lineEdit_home"))
        self.gridLayout_2.addWidget(self.lineEdit_home, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 4, 1, 1, 1)
        self.lineEdit_ak = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_ak.setText(_fromUtf8(""))
        self.lineEdit_ak.setObjectName(_fromUtf8("lineEdit_ak"))
        self.gridLayout_2.addWidget(self.lineEdit_ak, 4, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 4, 4, 1, 1)
        self.pushButton_ak = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_ak.setObjectName(_fromUtf8("pushButton_ak"))
        self.gridLayout_2.addWidget(self.pushButton_ak, 4, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 3, 1, 1, 1)
        self.pushButton_juli = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_juli.setObjectName(_fromUtf8("pushButton_juli"))
        self.gridLayout_2.addWidget(self.pushButton_juli, 3, 3, 1, 1)
        self.pushButton_city = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_city.setObjectName(_fromUtf8("pushButton_city"))
        self.gridLayout_2.addWidget(self.pushButton_city, 0, 3, 1, 1)
        self.lineEdit_work = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_work.setText(_fromUtf8(""))
        self.lineEdit_work.setObjectName(_fromUtf8("lineEdit_work"))
        self.gridLayout_2.addWidget(self.lineEdit_work, 1, 2, 1, 1)
        self.lineEdit_city = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_city.setText(_fromUtf8(""))
        self.lineEdit_city.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_city.setObjectName(_fromUtf8("lineEdit_city"))
        self.gridLayout_2.addWidget(self.lineEdit_city, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 1, 1, 1)
        self.lineEdit_juli = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_juli.setText(_fromUtf8(""))
        self.lineEdit_juli.setObjectName(_fromUtf8("lineEdit_juli"))
        self.gridLayout_2.addWidget(self.lineEdit_juli, 3, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.pushButton_work = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_work.setObjectName(_fromUtf8("pushButton_work"))
        self.gridLayout_2.addWidget(self.pushButton_work, 1, 3, 1, 1)
        self.lineEdit_houses = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_houses.setText(_fromUtf8(""))
        self.lineEdit_houses.setObjectName(_fromUtf8("lineEdit_houses"))
        self.gridLayout_2.addWidget(self.lineEdit_houses, 5, 5, 1, 1)
        self.pushButton_homes = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_homes.setObjectName(_fromUtf8("pushButton_homes"))
        self.gridLayout_2.addWidget(self.pushButton_homes, 5, 6, 1, 1)
        self.pushButton_money = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_money.setObjectName(_fromUtf8("pushButton_money"))
        self.gridLayout_2.addWidget(self.pushButton_money, 5, 3, 1, 1)
        self.lineEdit_money = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_money.setText(_fromUtf8(""))
        self.lineEdit_money.setObjectName(_fromUtf8("lineEdit_money"))
        self.gridLayout_2.addWidget(self.lineEdit_money, 5, 2, 1, 1)
        self.lineEdit_HOUSE_NUMBER_SET = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_HOUSE_NUMBER_SET.setText(_fromUtf8(""))
        self.lineEdit_HOUSE_NUMBER_SET.setObjectName(_fromUtf8("lineEdit_HOUSE_NUMBER_SET"))
        self.gridLayout_2.addWidget(self.lineEdit_HOUSE_NUMBER_SET, 4, 5, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 5, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 5, 4, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 2, 1, 1, 1)
        self.label_img = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_img.sizePolicy().hasHeightForWidth())
        self.label_img.setSizePolicy(sizePolicy)
        self.label_img.setMinimumSize(QtCore.QSize(152, 152))
        self.label_img.setMaximumSize(QtCore.QSize(152, 167))
        self.label_img.setText(_fromUtf8(""))
        self.label_img.setPixmap(QtGui.QPixmap(_fromUtf8("D:\\search_house\\wechat1.png")))
        self.label_img.setObjectName(_fromUtf8("label_img"))
        self.gridLayout.addWidget(self.label_img, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.pushButton_search.setText(_translate("Form", "查找", None))
        self.label_11.setText(_translate("Form", "    进度条(仅供参考)", None))
        self.groupBox.setTitle(_translate("Form", "显示框", None))
        self.textBrowser_display.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; color:#ff007f;\">参数信息显示框</span></p></body></html>", None))
        self.textBrowser_play.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; color:#ff007f;\">房源信息显示框</span><span style=\" font-size:14pt; font-weight:600; color:#ff007f;\">-[</span><span style=\" font-size:12pt; font-weight:600; color:#ff007f;\">因map-api误差与同名房屋存在，房源信息仅供参考</span><span style=\" font-size:14pt; font-weight:600; color:#ff007f;\">]</span></p></body></html>", None))
        self.groupBox_2.setTitle(_translate("Form", "设置区", None))
        self.pushButton_home.setText(_translate("Form", "保存", None))
        self.label_7.setText(_translate("Form", "公寓页数（每页20个公寓）", None))
        self.label_5.setText(_translate("Form", "高德地图ak码：[高德地图api申请]", None))
        self.label_9.setText(_translate("Form", "查找公寓个数[小于等于20]", None))
        self.pushButton_ak.setText(_translate("Form", "保存", None))
        self.label_2.setText(_translate("Form", "工作地点:", None))
        self.label_4.setText(_translate("Form", "工作地点范围（KM）[在该范围筛选]", None))
        self.pushButton_juli.setText(_translate("Form", "保存", None))
        self.pushButton_city.setText(_translate("Form", "保存", None))
        self.label_3.setText(_translate("Form", "房屋居室（一居为整租其他为合租）", None))
        self.label.setText(_translate("Form", "查询城市:", None))
        self.pushButton_work.setText(_translate("Form", "保存", None))
        self.pushButton_homes.setText(_translate("Form", "保存", None))
        self.pushButton_money.setText(_translate("Form", "保存", None))
        self.label_6.setText(_translate("Form", "月租金最高限额：", None))
        self.label_8.setText(_translate("Form", "房屋页数（每页20个房型）", None))

